POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "telegramm_account": "@banan4ik",
  "username": "Forester"
}
###

GET http://127.0.0.1:8000/user

###

DELETE http://127.0.0.1:8000/user/160

###
POST http://127.0.0.1:8000/theme
Content-Type: application/json

{
  "name": "Работа",
  "user_id": 162
}

###
GET http://127.0.0.1:8000/theme/161

###
GET http://127.0.0.1:8000/theme

###
DELETE http://127.0.0.1:8000/theme/84

###
POST http://127.0.0.1:8000/surveillance
Content-Type: application/json

{
  "name": "Начальник",
  "user_id": 162
}

###
GET http://127.0.0.1:8000/surveillance/161

###
GET http://127.0.0.1:8000/surveillance

###
DELETE http://127.0.0.1:8000/surveillance/55