POST http://127.0.0.1:8000/user/register
Content-Type: application/json

{
  "telegramm_account": "@banan4ik",
  "username": "Forester"
}
###

GET http://127.0.0.1:8000/user/get_all_users/

###
GET http://127.0.0.1:8000/user/get_user/?telegramm_account=@banan4ik

###
DELETE http://127.0.0.1:8000/user/?user_id=1

###
POST http://127.0.0.1:8000/theme
Content-Type: application/json

{
  "name": "ЖКХ",
  "user_id": 1
}

###
GET http://127.0.0.1:8000/theme/show_user_themes/?user_id=1

###
GET http://127.0.0.1:8000/theme/show_all_themes/

###
DELETE http://127.0.0.1:8000/theme/?theme_id=7

###
POST http://127.0.0.1:8000/surveillance
Content-Type: application/json

{
  "name": "Жена",
  "user_id": 1
}

###
GET http://127.0.0.1:8000/surveillance/show_user_surveillances/?user_id=1

###
GET http://127.0.0.1:8000/surveillance/show_all_surveillances/

###
DELETE http://127.0.0.1:8000/surveillance/?surveillance_id=1

###
POST http://127.0.0.1:8000/complain
Content-Type: application/json

{
  "user_id": 1,
  "theme_id": 2,
  "surveillance_id": 1
}

###
GET http://127.0.0.1:8000/complain/show_all_complains/

###
GET http://127.0.0.1:8000/complain/show_user_complains/?user_id=1

###
DELETE http://127.0.0.1:8000/complain/?complain_id=1