POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "telegramm_account": "@banan4ik",
  "username": "Forester"
}
###

GET http://127.0.0.1:8000/user

###

DELETE http://127.0.0.1:8000/user/160

###
POST http://127.0.0.1:8000/theme
Content-Type: application/json

{
  "name": "Работа",
  "user_id": 162
}

###
GET http://127.0.0.1:8000/theme/162

###
GET http://127.0.0.1:8000/theme

###
DELETE http://127.0.0.1:8000/theme/84

###
POST http://127.0.0.1:8000/surveillance
Content-Type: application/json

{
  "name": "Начальник",
  "user_id": 162
}

###
GET http://127.0.0.1:8000/surveillance/162

###
GET http://127.0.0.1:8000/surveillance

###
DELETE http://127.0.0.1:8000/surveillance/55

###
POST http://127.0.0.1:8000/complain
Content-Type: application/json

{
  "user_id": 162,
  "theme_id": 86,
  "surveillance_id": 56
}

###
GET http://127.0.0.1:8000/complain/162

###
GET http://127.0.0.1:8000/complain

###
DELETE http://127.0.0.1:8000/complain/47