
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - appnet

  app:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
        - ./.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
networks:
  appnet:
    name: appnet
    driver: bridge

