"""create complain table

Revision ID: 9487c82dc240
Revises: 
Create Date: 2024-10-09 16:35:35.226855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9487c82dc240"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complain_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("who", sa.String(length=30), nullable=False),
        sa.Column("whom", sa.String(length=30), nullable=False),
        sa.Column("about", sa.String(length=30), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complain_table")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complain_table")
    # ### end Alembic commands ###
