"""create surveilance table

Revision ID: 13d2b69327c8
Revises: 6bcf2fcd6e4c
Create Date: 2024-10-20 15:31:20.399778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13d2b69327c8"
down_revision: Union[str, None] = "6bcf2fcd6e4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveillance_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_surveillance_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surveillance_table")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surveillance_table")
    # ### end Alembic commands ###
