"""create complain table

Revision ID: fd234612ae9e
Revises: 13d2b69327c8
Create Date: 2024-10-20 15:44:14.431217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd234612ae9e"
down_revision: Union[str, None] = "13d2b69327c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complain_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_complain_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complain_table")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complain_table")
    # ### end Alembic commands ###
