"""create fk from complain to theme table

Revision ID: fef829a44ef7
Revises: af4d02da03c7
Create Date: 2024-10-20 16:01:28.462909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fef829a44ef7"
down_revision: Union[str, None] = "af4d02da03c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complain_table", sa.Column("theme_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_complain_table_theme_id_theme_table"),
        "complain_table",
        "theme_table",
        ["theme_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_complain_table_theme_id_theme_table"),
        "complain_table",
        type_="foreignkey",
    )
    op.drop_column("complain_table", "theme_id")
    # ### end Alembic commands ###
