"""check tables

Revision ID: 924ad0d3286f
Revises: 
Create Date: 2024-10-23 02:45:22.750642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "924ad0d3286f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegramm_account", sa.String(length=30), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_table")),
        sa.UniqueConstraint(
            "telegramm_account", name=op.f("uq_user_table_telegramm_account")
        ),
    )
    op.create_table(
        "surveillance_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_surveillance_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surveillance_table")),
    )
    op.create_table(
        "theme_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_theme_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_table")),
    )
    op.create_table(
        "complain_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.Column("surveillance_id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["surveillance_id"],
            ["surveillance_table.id"],
            name=op.f("fk_complain_table_surveillance_id_surveillance_table"),
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme_table.id"],
            name=op.f("fk_complain_table_theme_id_theme_table"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_complain_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complain_table")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complain_table")
    op.drop_table("theme_table")
    op.drop_table("surveillance_table")
    op.drop_table("user_table")
    # ### end Alembic commands ###
