"""create theme table

Revision ID: af4d02da03c7
Revises: 03f947b73848
Create Date: 2024-10-20 15:56:45.634613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4d02da03c7"
down_revision: Union[str, None] = "03f947b73848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
            name=op.f("fk_theme_table_user_id_user_table"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_table")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("theme_table")
    # ### end Alembic commands ###
