"""create fk from complain to surveillance table

Revision ID: 03f947b73848
Revises: fd234612ae9e
Create Date: 2024-10-20 15:47:58.374885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03f947b73848"
down_revision: Union[str, None] = "fd234612ae9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complain_table",
        sa.Column("surveillance_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_complain_table_surveillance_id_surveillance_table"),
        "complain_table",
        "surveillance_table",
        ["surveillance_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_complain_table_surveillance_id_surveillance_table"),
        "complain_table",
        type_="foreignkey",
    )
    op.drop_column("complain_table", "surveillance_id")
    # ### end Alembic commands ###
